import mysql.connector as sqltor
mycon = sqltor.connect(host="localhost", user="root", passwd="123456", auth_plugin='mysql_native_password',database="foodzone")
if mycon.is_connected():
        print("Database Connection Successful")
else:
     print("Database Connection Error")
# Enter your personal details
mn = input("Enter your mobile number")
ln=len(mn)
if ln>10 or ln<10:
    print("Enter valid mobile number")
else:
    n = input("Enter your name")
    dob = input("Enter your date of birth(YYYY-MM-DD)")
    st = input("Enter your state")
    ffd = input("Enter your favourite food dish")

cursor = mycon.cursor()
sq = "INSERT INTO ulogin(MobileNo,Name,DOB,State,Favourite_FoodDish) VALUES('{}','{}','{}','{}','{}')".format(mn, n,dob, st,ffd)
cursor.execute(sq)
mycon.commit()
mycon.close()
ex="0"
while ex!="exit":
    # Choosing the region
    print("For north indian recipe press N")
    print("For south indian recipe press S")
    print("For western india recipe press W")
    print("For eastern india recipe press E")
    r = input("Enter the region you desire")
     # Checking the region
    if r == 'N'or r=='n':
        print("1.Cholle Bhature")
        print("2.Rajma Chawal")
        print("3.Butter Paneer Masala")
        print("4.Kulche")
        print("5.Dal Tadka")

        # Input of the dish
        d = int(input("Enter the desired dish number"))
        if d == 1:
            print("The recipe of Bhature is:")
            print("1. You will have to start the night before. In a bowl take fresh yogurt (curd), sugar, baking powder and all purpose flour (maida). Mix well all the above 4 ingredients.")
            print("2. Cover the bowl with a cloth or lid and set it aside in a warm place overnight or for 8 to 9 hours to allow natural fermentation to take place. The next day you will see tiny bubbles on the surface of the mixture. I stirred the mixture and so the bubbles cannot be seen in this picture.")
            print("3. In another bowl, mix together the wheat flour with salt and rub the oil or ghee or butter into it with your fingertips.")
            print("4. Into this bowl, add the fermented mixture and the warm water.")
            print("5. Mix everything well.")
            print("6. Knead into a dough for 5 to 10 minutes or until it is smooth. Add a little flour if it is too wet.")
            print("7. Gather the dough into a compact ball and cover it with a damp cloth. Again set it aside in a warm place for 2 hrs. This is how the dough appears after 2 hours.")
            print("8. Knead the dough again. Shape into 12 to 15 balls.")
            print("9. Roll each into 4 to 5 inch discs.")
            print("10. Heat oil or ghee and deep fry the bhatura in the same way as you would fry pooris. The oil has to be moderately hot. Use medium to medium-high flame while frying. When one side is golden, gently flip and fry the second side.")
            print("11. Fry them till golden and crisp. The bhatura will take a bit longer to fry than Poori.")
            print("12. Drain them on kitchen paper napkins to remove the excess oil.")
            print("The recipe of chole is:")
            print("1. In a pressure cooker add the soaked and drained chickpeas, around 5 cups water, 2 tea bags, bay leaves, cardamom, cinnamon stick and some salt. Pressure cook at high flame till you get 1-2 whistles. After that lower the flame to medium and let the chickpeas cook for another 10-12 minutes. Remove the cooker from heat and allow it to cool down. Once the steam is gone, open the cooker and check the chickpeas. You should be able to press them easily with your fingers. If not, close the cooker and cook for 2 more whistles.")
            print("2. In a wok, heat 2 tsp of oil. Once hot, add cloves and grated onions. Fry the onions till the raw smell goes away and they are light golden brown in color.")
            print("3. Add ginger-garlic paste and cook for 3-4 minutes till the smell of ginger-garlic goes away.")
            print("4. Now add the tomato puree , stir and let it cook for 12-15 minutes on medium-low flame. Cover the pan to prevent splash all around. This step in my opinion is very important. The tomatoes need to be cooked really well till the raw smell goes away completely. So have patience and let them cook for around 15 minutes.")
            print("5. Add the chole masala, red chilli powder, paprika powder, cumin powder, salt and mix for a 1-2 minutes.")
            print("6. Drain the the chickpeas and add them to the tomato-onion mixture, stir till all the chickpeas are coated with spices, around 2 minutes. Do not throw away the water once you have drained the chickpeas. We will add the same water in the gravy.")
            print("7. Add water, cover the pan and let it simmer at medium-low flame for around 30 minutes. The gravy will thicken after 30 minutes so add water accordingly. I do not like thin gravy with chole but if you do add more water than what is mentioned in the recipe.")
            print("8. To temper, heat 1 tbsp of ghee in a pan and the ginger julienne to it.")
            print("9. Fry till the juliennes are golden brown in color but do not burn them. Add to the chole curry, mix and switch off the flame.")
        elif d == 2:
            print("The recipe of rajma is:")
            print("1. Soak rajma overnight and pressure cook till they are soft")
            print("2. Chop onion-tomato and make ginger-garlic paste")
            print("3. In a deep bottomed pan, add mustard oil, when it gets heated add green cardamom, black cardamom, cinnamon, clove, peppercorn. Once they become fragrant, add onions and cook till they are golden brown. ")
            print("4. Now add the tomatoes and cook on high for 4-5 minutes. Add ginger- garlic-chilli paste, cumin powder, coriander powder and black pepper powder. Cook till the spices become fragrant and oil starts leaving the sides of the pan.")
            print("5. Now add the rajma and one cup of water. Mix well and cook covered for 10 minutes. Once done, add the ghee. You can garnish with coriander leaves. Your rajma is ready.")
            print("6. To make steamed rice without using a pressure cooker, wash 1 cup rice in running water. Then, add them in a large and deep-bottomed pan with 4-5 cups of water in it. You can also add a little salt in it for taste. ")
            print("7. Once the rice is soft and double its size, strain the water. Spread the rice on a plate and allow it to cool for 2-3 minutes. Once the rice is done, serve hot with prepared Rajma.")
        elif d == 3:
            print("The recipe of Butter Paneer Masala")
            print("1. Firstly, in a large kadai heat 1 tsp butter and 1 tsp oil.")
            print("2. Saute 1 onion, 1 inch ginger and 3 clove garlic until it shrinks slightly.")
            print("3. Now add 2 tomato and 10 cashew for a minute.")
            print("4. Cover and cook for 10 minutes or until tomatoes turn soft and mushy.")
            print("5. Cool completely and transfer to the blender.")
            print("6. Blend to smooth paste adding water if required.")
            print("7. In a kadai heat 2 tbsp butter and saute 2 pods cardamom and 1 bay leaf.")
            print("8. Keeping the flame on low add ¼ tsp turmeric, 1 tsp chilli powder, ¼ tsp garam masala and ¼ tsp cumin powder.")
            print("9. Saute until the spices turn aromatic without burning.")
            print("10.Add in prepared onion tomato paste and saute well.")
            print("11.Saute until oil separates from sides.")
            print("12.Further add 1 cup water, ½ tsp sugar and 1 tsp salt.")
            print("13.Mix well adjusting consistency as required.")
            print("14.Also, add 2 tbsp cream and mix well.")
            print("15.Now add 20 cubes of paneer and mix gently.")
            print("16.Cover and simmer for 10 minutes or until flavours are absorbed.")
            print("17.Further add 2 tbsp coriander, ½ tsp kasuri methi and ¼ tsp garam masala. mix well.")
            print("18.Finally, enjoy paneer butter masala with roti or naan.")
        elif d == 4:
            print("The recipe of kulche is:")
            print("1. To prepare the dough, take a large bowl and sieve the flour in it. Add baking powder, baking soda, curd and refined oil in it. ")
            print("2. Add sugar and salt in the flour and mix it well with your fingers. Add warm milk in flour and knead the mixture to prepare a firm dough. Cover it with a damp cloth and keep it aside.")
            print("3. To make the stuffing for the kulcha, take the boiled potato and mash it in a bowl. Combine finely chopped onions and green chillies with mashed potato. ")
            print("4. Add chat masala, coriander leaves, red chilli powder and cumin powder in the mixture. Sprinkle salt and mix the ingredients with a spoon.")
            print("5. Now take the dough and divide it into two equal portions. Roll each portion into a ball and then flatten the ball using a rolling pin.")
            print("6. Place a spoonful of aloo filling in the centre of the flatten dough and close the kulcha well. Sprinkle some flour over it and roll it again into a paratha.")
            print("7. Take a non-stick pan, add olive oil and heat it over medium flame. When oil bubbles start to rise, gently place the kulcha in the pan and cook for a minute.")
            print("8. Flip the kulcha and cook the other side till both sides turn crispy and golden brown in colour. Once done, serve hot with Amritsari Chole.")
        elif d == 5:
            print("The recipe of dal tadka:")
            print("1. Firstly, in a pressure cooker take ½ cup toor dal, 2 tbsp masoor dal. you can also add moong dal if you prefer.")
            print("2. Also add ¼ tsp turmeric, ½ tsp salt, 1 tsp oil and 1½ cup water.")
            print("3. Pressure cook for 5 whistles or until dal is cooked well.")
            print("4. Add 1 cup water and adjust consistency. keep aside. ")
            print("5. Now in a large kadai heat 2 tbsp ghee and splutter ½ tsp cumin, 1 bay leaf, pinch hing and 2 dried red chilli.")
            print("6. Also add 2 clove garlic, 1 inch ginger, 1 chilli and saute slightly.")
            print("7. Further add 1 onion and saute until it turns golden brown.")
            print("8. Keeping the flame on low add ¼ tsp turmeric, ½ tsp chilli powder, ½ tsp coriander powder and ½ tsp salt.")
            print("9. Add 1 tomato and saute until it turns soft and mushy.Add in cooked dal and stir well adjusting consistency as required.")
            print("10.Simmer for 5 minutes or until flavours are well combined.")
            print("11.Now add 2 tbsp coriander, 1 tsp kasuri methi and ¼ tsp garam masala. Mix well.");
            print("12.Finally, enjoy dal tadka with jeera rice or steamed rice.")
        else:
            print("Undefined character entered")
    if r == 'S' or r=='s':
        print("1.Idli")
        print("2.Masala Dosa")
        print("3.Spicy Sambhar")
        print("4.Medu Vada")
        print("5.Appam")

        # Input of the dish
        d = int(input("Enter the desired dish number"))
        if d == 1:
            print("The recipe of idli is:")
            print("1. Firstly, in a large bowl soak 1 cup urad dal for 4 hours.")
            print("2. Drain off the water and transfer to blender or grinder.")
            print("3. Blend to smooth and fluffy batter adding water as required.")
            print("4. Transfer the batter to a large bowl. Keep aside.")
            print("5. Now in another bowl take 2 cup idli rava.")
            print("6. Rinse the idli rava with enough water and drain off the water.")
            print("7. Repeat this for 2 or 3 times or till water runs clean.")
            print("8. Squeeze off water from idli rava and add to urad dal batter.")
            print("9. Mix well making sure rava and urad dal are combined well.")
            print("10.Now cover and rest in warm place for 8-10 hours or till the batter ferments and doubles.After 8 hours, batter doubles indicating well fermented with air pockets present.")
            print("11.Add 1 tsp salt to the batter and mix gently without disturbing the air pockets.")
            print("12.Scoop the batter into idli plate greased with oil. Place in steamer and steam for 10 minutes on medium flame or till a toothpick inserted comes out clean.")
            print("13.Finally, soft idli recipe are ready to serve along with chutney and sambar.")
        elif d == 2:
            print("The recipe of masala dosa:")
            print("a.Masala Dosa Batter preparation:")
            print("1. Firstly, in a large bowl take 3 cup sona masuri rice and ½ tsp methi.")
            print("2. Rinse well and soak in enough water for 4 hours.In another bowl take 1 cup urad dal, 2 tbsp toor dal and 2 tbsp chana dal.Rinse well and soak in enough water for 2 hours.")
            print("3. After soaking dal for 2 hours, drain off the water and transfer to the grinder. You can also grind in mixi if you do not have access to a grinder.")
            print("4. Add water as required and blend to smooth paste scrape sides. The smooth and fluffy batter will be ready after 40 minutes.")
            print("5. Transfer the batter to a large vessel and keep aside.In the same grinder add soaked rice and 1 cup rinsed poha.Add water slowly and scrape the sides. Blend to a coarse paste.")
            print("6. Transfer the rice batter to the same urad dal batter.Mix well making sure everything is well combined.")
            print("7. Ferment in a warm place for at least 8 hours or until the batter doubles in volume. If you are leaving in a cold climate, then you can place the batter in the warm oven (just heat the oven until it turns slightly warm and then turn off) to ferment.")
            print("8. Once the batter is well fermented, mix gently, without disturbing the air pockets.")
            print("9. Transfer 4 cups of fermented batter to a small bowl and add 1 tsp salt.Mix well until the salt is well combined. masala dosa batter is ready. keep aside.")
            print("b.Aaloo Bhaji preparation")
            print("1. Firstly, in a large kadai heat 2 tbsp oil and splutter 1 tsp mustard, 1 tsp urad dal, 1 tsp chana dal, 1 dried red chilli, few curry leaves, pinch hing.")
            print("2. Now add 2 chilli and 1 inch ginger. Saute well.Also, add 1 onion and saute until onions shrink slightly.Further, add ¼ tsp turmeric and 1 tsp salt. Saute well.")
            print("3. Now add 3 potato and mix well, mash slightly making sure everything is well combined.")
            print("4. Turn off the flame and add 2 tbsp coriander and 2 tbsp lemon juice. Mix well and aloo bhaji for masala dosa is ready. keep aside.")
            print("c.Masala Dosa preparation")
            print("1. Firstly, add a ladleful of batter on hot tawa.Spread as thin as possible making a crispy dosa.")
            print("2. Take 1 tsp of butter and spread uniformly.Also, place 2 tbsp of prepared aloo masala in the centre.")
            print("3. Roast until the dosa turns golden brown and crisp.")
            print("4. Scrape the sides of dosa and roll the dosa.Finally, masala dosa recipe is ready to serve with coconut chutney and sambar.")
        elif d == 3:
            print("The recipe of sambhar is:")
            print("1. Firstly, in a pressure cooker add ½ cup of toor dal with 2 cups of water. Also add pinch of turmeric. Pressure cook it for 5 whistles. ")
            print("2. Meanwhile, in a small bowl take small half lemon sized tamarind and soak in water. Also, prepare and chop veggies like carrot, eggplant, drumstick, onions and tomatoes.")
            print("3. Now, in a large kadai take the tamarind water.To that add 1 tsp of jaggery/sugar along with green chill, salt and turmeric powder.")
            print("4. Furthermore, add all the chopped vegetables to same mixture.")
            print("5. Meanwhile, once the dal is cooked mash it well.After 10 minutes, the vegetables should be cooked properly.")
            print("6. Now add the mashed toor dal and bring it to boil.Add 2 tsp of sambhar powder.Mix the sambar powder and bring it to boil.")
            print("7. Prepare the tempering by heating urad dal, mustard seeds, hing, curry leaves and red chillies.")
            print("8. Add the tempering to the freshly prepared sambar.Finally, sambar is ready.")
        elif d == 4:
            print("The recipe of Medu Vada:")
            print("1. Wash and soak dal in about 3 cups of water for about 2-3 hours.")
            print("2. Drain all the water from soaked dal. grind urad dal and channa dal together to smooth paste using very little water")
            print("3. The batter should be thick and use very little water. the right consistency is very important or otherwise, you will not be able to get the vada shape.")
            print("4. Add coriander, green chilli, ginger and chopped dry coconut to the batter. Mix it very well.")
            print("5. Add 2-3 tsp of rice flour. rice flour is added to make it crispy.Add pinch of hing to make it more digestible.")
            print("6. Heat the oil in a frying pan in medium flame. Wet your palms and take a lemon size batter.")
            print("7. Make hole in the center and slide it into the hot oil.")
            print("8. The vada should float on top of oil.Make sure your oil is not too hot. otherwise the vadas would not cook evenly.")
            print("9. Fry on both sides till it becomes golden brown in colour.")
            print("10.Serve medu vada immediately with chutney collections or sambar collections.")
        elif d ==5:
            print("The recipe of appam is:")
            print("1. Firstly, soak idli rice and methi seeds for 5 hours. ")
            print("2. In a blender take soaked rice, add thin poha and coconut.")
            print("3. Add water as required and blend to smooth batter.")
            print("4. To activate yeast, in a large bowl take warm water, dry yeast and sugar.Rest for 5 minutes.")
            print("5. Now transfer the blended batter into the yeast water.Mix well and ferment the batter for 8 hours.Mix the batter slightly,also add salt as and water.")
            print("6. The batter has to be in flowing consistency.")
            print("7. Now, pour a ladleful of aapam batter on to the medium hot pan.Immediately, rotate and spread.")
            print("8. Cover and simmer till the appam gets cooked well completely in presence of steam.")
            print("9. Finally, serve kerala style appam with chutney / kadala curry.")
        else:
            print("Undefined Character Entered")
    if r == 'W' or r=='w':
        print("1.Dhokla")
        print("2.Sev Usal")
        print("3.Sev Khamani")
        print("4.Dabeli")
        print("5.Pav Bhaji")

        # Input of the dish
        d = int(input("Enter the desired dish number"))
        if d == 1:
            print("The recipe of Dhokla is:")
            print("1. Take a large mixing bowl and add gram flour, salt, water, lemon juice and baking soda in it. Mix all these ingredients well. ")
            print("2. Allow the batter to ferment for 1-2 hours. If you are making it in the winter season.")
            print("3. Pour the dhokla batter in the greased utensil and cook on low flame for 15-20 minutes")
            print("4. Check with a knife after 15 minutes by inserting it inside the dhokla. If the knife comes out clean, remove it from the stove. Allow the dish to cool and then cut into squares.")
            print("5. For the tempering, heat a pan with oil in it over medium flame. Once the oil is sufficiently hot, add mustard seeds, curry leaves and vertically sliced green chilli.")
            print("6. Add 1/2 cup of water in the pan and allow it to boil. On 2-3 boils, lower the flame and squeeze 1/2 lemon, add sugar and green coriander leaves. ")
            print("7. Turn off the heat and pour the tempering on the dhokla and sprinkle the coconut powder over the dish.")
            print("8. Transfer the dish to a plate and serve it with any spicy chutney that you like such as green coriander chutney.")
        elif d == 2:
            print("The recipe of Sev Usal is:")
            print("1. Rinse the dried green peas with water properly.Soak them into fresh water and heat the water for 10 minutes. Keep it aside for overnight or 6-8 hours.")
            print("2. Pressure cook the soaked peas for 6 – 7 whistles or till get boiled. Then keep it on simmer for 10 minutes. While boiling the dried peas add 1 tsp salt.")
            print("3. Meanwhile chop the onion, tomatoes and green chilies. Make a paste of ginger and garlic in mortar-pastel. Boil the potatoes, peel them and chop them into medium size cubes.")
            print("4. Heat the oil into one pan.Add mustard seeds when oil is medium hot.When mustard seeds start to splutter, add cumin seeds.When cumin seeds start to crackle, add hing, curry leaves and green chilies.")
            print("5. Saute for a minute, add chopped onions. Mix well.aute till onion starts to get soften and add ginger-garlic paste. Do not overcook the onion.")
            print("6. Saute till raw aroma of ginger and garlic goes away. Add tomatoes. Mix well.")
            print("7. Add all dry spices and salt. Cook till tomatoes get soften.Add chopped boiled potatoes. Mix well. Cook for 2 minutes. Add jaggery ( optional ) at this stage.")
            print("8. Meanwhile heat the boiled peas once again. Add 1 cup water if required.Add prepared masala into boiled green peas. Mix well.")
            print("9. Cook them for 5 – 10 minutes.Turn off the flame. Add chopped coriander leaves.")
            print("10.Now your ragda or usal for sev usal is ready to serve. You can start plating.")
            print("11.Pour ragada into plate. Sprinkle sev, add meethi chutney ( optional ). Garnish the sev usal with chopped onion and coriander leaves.")
        elif d == 3:
            print("The recipe of Sev Khamani is:")
            print("1. Soak chana dal for 5-6 hours")
            print("2. Next, take a large-sized pan and place it on medium-low flame. Then, pour and heat oil in it.")
            print("3. Now, add mustard seeds and stir them for 5-10 seconds. Next, add the ginger paste along with green chilli paste, sugar, lemon juice and mix well. Also, add salt as required. Stir well for about 10-12 minutes and then keep aside.")
            print("4. After the dal is soaked in water for at least 5-6 hours, drain the water from its bowl. ")
            print("5. Now, transfer the soaked dal in a mixer-grinder jar. Grind it at maximum speed until it becomes partially smooth in texture.")
            print("6. Next, take a separate large-sized pan and place it on medium flame. Now, transfer the blended dal in the pan and stir well until it reaches the boiling temperature. ")
            print("7. Make sure that the dal is cooked properly and is tender in texture. Also, add salt as required and mix well. Once done, turn the flame off and keep aside.")
            print("8. Now, take a serving dish and transfer the prepared dal in it.Now, take a serving dish and transfer the prepared dal (step 4) in it")
        elif d == 4:
            print("The recipe of dabeli is:")
            print("a.Dabeli Masala preparation:")
            print("1. Firstly, in a pan take 1 tsp coriander seeds, ½ tsp cumin, ½ tsp fennel, ½ tsp pepper, ½ inch cinnamon, 1 pod black cardamom and 6 clove. ")
            print("2. Also, add 1 star anise, 1 bay leaf, 1 tsp sesame seed, 2 tbsp dry coconut and 3 dried red chilli.")
            print("3. Dry roast on low flame until the spices turn aromatic.Cool completely, and transfer to a small mixi jar.")
            print("4. Add ½ tsp turmeric, 1 tsp aamchur, 1 tsp sugar and ½ tsp salt.")
            print("5. Blend to a fine powder and dabeli masala is ready. keep aside.")
            print("b.Aloo mixture preparation")
            print("1. Firstly, in a large kadai heat 2 tbsp oil.")
            print("2. Now take 3 tsp of prepared dabeli masala into a small cup, along with 2 tbsp tamarind chutney and ¼ cup water.")
            print("3. Mix well making sure there are no lumps. pour in the masala mixture into the hot oil.")
            print("4. Cook for 2 minutes or until it turns aromatic.Further, add 3 potato, ½ tsp salt and mix well.")
            print("5. Mash and mix making sure everything are well combined.Transfer the mixture into a plate.")
            print("6. Top with 1 tbsp coconut, 1 tbsp coriander, 2 tbsp sev, 2 tbsp pomegranate and 2 tbsp spiced peanut.")
            print("c.Assembling Dabeli")
            print("1. Firstly, slit the pav in the centre and spread 1 tsp green chutney on one side of pav and 1 tsp of tamarind chutney on another side.")
            print("2. Stuff in prepared aloo dabeli mixture into the pav.Also stuff in 1 tsp of onion and aloo dabeli mixture.")
            print("3. Now toast the pav in butter making sure both sides turn slightly golden brown. ")
            print("4. Finally, roll the dabeli into sev and serve immediately.")
        elif d == 5:
            print("The recipe of Pav Bhaji:")
            print("1. Firstly, in a large kadai heat 1 tbsp butter and add vegetables. cook and mash well.")
            print("2. Now add 1 tsp chilli powder, ¼ tsp turmeric, 1 tsp pav bhajalso add 1 tbsp coriander leaves, 1 tsp ginger garlic paste, 1 onion and ½ lemon juice. saute well.i masala, 1 tsp kasuri methi and 2 tbsp coriander leaves.")
            print("3. Heat a tbsp of butter and add ¼ tsp chilli powder, ½ tsp pav bhaji masala, 1 tsp kasuri methi.")
            print("4. Also add 1 tbsp coriander leaves, 1 tsp ginger garlic paste, 1 onion and ½ lemon juice. saute well.")
            print("5. Now add 3 drops of red food colour and mix well")
            print("6. Finally, serve pav and bhaji as pav bhaji.")
        else:
            print("Undefined character entered")

    if r == 'E' or r=='e':
        print("1.Rasgulla")
        print("2.Litti Choka")
        print("3.Momos")
        print("4.Dalma")
        print("5.Thukpa")
        # Input of the dish
        d = int(input("Enter the desired dish number"))
        if d == 1:
            print("The recipe of rasgulla is:")
            print("1. Firstly, in a large vessel get 2 litre milk of milk to a boil stirring occasionally.")
            print("2. Once the milk comes to a boil, pour 2 tbsp lemon juice and stir well. you can alternatively use curd or vinegar.")
            print("3. Stir until the milk curdles keeping the flame on low to medium.")
            print("4. Do not boil further once water separates completely.")
            print("5. Drain the curdled milk over a cloth-lined over a colander. you can use the leftover water to make soup or knead the dough as they are very nutritious.")
            print("6. Squeeze off the water completely. be careful as the curdled milk will be very hot.")
            print("7. Rinse off the curdled milk with fresh water to remove sourness from lemon juice.")
            print("8. Squeeze off the water completely. do not over squeeze as the moisture in paneer will be lost.")
            print("9. Hang for 1 hour making sure the water is drained completely, yet remain the moisture.")
            print("10.After 1 hour, start to mash the paneer for 5 minutes.Mash the paneer till it turns out smooth texture without any grains of paneer.")
            print("11.Now prepare small ball sized paneer and keep aside. cover and keep to prevent from drying.")
            print("12.In a large vessel take 1 cup sugar, 5 cup water and 3 pod cardamom.Stir and dissolve the sugar completely.Now boil the water for 5 minutes.")
            print("13.Drop in rolled paneer balls one by one into boiling sugar water.Cover and boil for 10 minutes or until rasgulla doubles in size.")
            print("14.Now drop into ice-cold water immediately, to prevent from shrinking in size.")
            print("15.Once cooled completely, take into a serving bowl and pour in leftover sugar water.Finally, enjoy rasgulla chilled or as it is.")
        elif d == 2:
            print("The recipe of litti chokha is:")
            print("1. Pinch a small ball sized dough. press the edges and form a cup.Further place a ball sized sattu stuffing in the centre.")
            print("2. Start pleating the dough, making sure the stuffing is secured well.Pinch off excess dough and roll well.")
            print("3. Place the rolled litti in appe pan heated with oil. or preheat and bake in oven at 180 degree celcius for 45 minutes flipping in between.")
            print("4. Cover and cook on low flame for 10 minutes.Flip over and cook both sides. cook for approx 30 minutes in total")
            print("5. Continue to cook until the litti turns golden brown from all the sides and cooked from inside.")
            print("6. Finally, litti is ready to serve with chokha and ghee.")
        elif d == 3:
            print("The recipe of momos is:")
            print("1. Firstly, prepare stuffing by heating 3 tsp oil and saute 3 clove garlic, 1 inch ginger and 2 chilli.Also, add 2 tbsp spring onion and saute on high flame.")
            print("2. Further, add 1 cup carrot and 2 cup cabbage. stir fry on high flame.Now add ½ tsp pepper and ½ tsp salt.")
            print("3. Additionally, 2 tbsp spring onion and stuffing mixture is ready.Further, pinch a small ball sized momos dough and flatten.")
            print("4. Now dust with some maida and start to roll using a rolling pin.")
            print("5. Roll to almost medium thin circle. around 4 – 5 inch in diameter. make sure you roll from sides and keep the centre slightly thick.")
            print("6. Now place a heaped tbsp of prepared stuffing in the centre.Start pleating the edges slowly and gather everything.")
            print( "7. Press in middle and seal the momos forming a bundle.Press in middle and seal the momos forming a bundle.")
            print("8. Heat a steamer and arrange the momos in the tray without touching each other.Furthermore, steam momos for 10-12 minutes or till shiny sheen appears over it.")
            print("9. Finally, veg momos recipe is ready to enjoy with momos chutney.")
        elif d == 4:
            print("The recipie of Dalma is:")
            print("1. To prepare this easy recipe, cut the vegetables in big square size and keep the beans long.")
            print("2. Wash the daal properly then heat your container and add 3 glass of water. Put bay leaves, salt and turmeric powder into it let them boil for a minute or two. Then add the daal and cook well.")
            print("3. After cooking the daal properly, add the vegetables and half cover it. After cooking for a few minutes add crushed ginger and jaggery (as per your taste).")
            print("4. After the vegetables get cooked, add grated coconut (keep some for garnishing) and cook for another 5-10 minutes.")
            print("5. Heat ghee in a pan and then turn off the flame. Add cumin seeds and asafoetida in the hot ghee, instantly pour it into the dal and cover completely for a minute. ")
            print("6. Then mix it and garnish with grated coconut and coriander leaves. (Note: This tempering is made without garlic and onion.)")
        elif d == 5:
            print("The recipe of Thukpa is:")
            print("1. Boil the Noodles as per the instructions and keep it aside.")
            print("2. In a wok, add in the oil.Once hot add the garlic and ginger and saute it for 30 seconds.")
            print("3. Now add the green onion and saute until translucent.Now add the chopped carrot, cabbage and green beans.")
            print("4. Saute on high heat for 3-4 minutes.")
            print("5. Add in the mushrooms and saute for a minute.")
            print("6. Now add the cumin powder, Garam Masala Powder, Red Chilly Sauce and Soya Sauce.")
            print("7. Add the water and let the mixture come to a boil.Add in the boiled noodles and salt.")
            print("8. One can adjust the quantity of spices as per their preference.Garnish with spring onions and serve.")
        else:
            print("Undefined character entered")
    else:
        print("Undefined character entered")

    ex=input("Press exit to exit or press ENTER to continue")
